### ISSUE TITLE
Feature request: On/Off switch or passthrough in admin

### ISSUE THREAD

**Issue by adioe3** [technodelight/zenc-email-logger#10]
I really like this module but I'd like it much more if it had an "on/off" switch or a passthrough (save + send) in admin. IMHO, putting that option under `Configuration` -> `Store Email Addresses` would be okay(ish). 

I believe the only code change would then be in `Zenc_EmailLogger_Model_Core_Email_Template::getMail()`, something like this:

```
    public function getMail()
    {
        if (Mage::getStoreConfigFlag('amazing/switch/path')) {
            return parent::getMail();
        }
        if (is_null($this->_mail)) {
            $this->_mail = Mage::getModel('zenc_emaillogger/zend_mail_logger');
        }
        return $this->_mail;
    }
```

Can this be added?

**Comment by adioe3** [comment]
PR: https://github.com/technodelight/zenc-email-logger/pull/11

**Comment by technodelight** [comment]
Great job. Many many thanks for contributing!
